### ISSUE TITLE
Error while navigating to 'preparation/athletes'

### ISSUE THREAD

**Issue by janghelsaket758** [jflamy/owlcms4#1009]
While trying to navigate to the 'preparation/athletes' page, an exception was thrown with the following message: "could not prepare statement".
Steps to Reproduce:

Open the application.
Navigate to 'preparation/athletes'.
Observe the error message displayed on the screen.
Expected Behavior:
The 'preparation/athletes' page should load without any exceptions.

Actual Behavior:
An error message is displayed: "could not prepare statement".

Screenshot:
(Include the screenshot you provided)

Environment:

Application Version: [49.1]
Browser: [Chrome]
Operating System: [Windows 10]
Additional Information:
(Any other relevant information, such as recent changes to the system, database state, etc.)

You can fill in the placeholders with the specific details of your environment and any additional information that might help in diagnosing the issue.

![error](https://github.com/jflamy/owlcms4/assets/142079970/da53016f-8c46-4c55-8904-047417fc22e5)

**Comment by jflamy** [comment]
Please provide an export of the database to owlcms-bugs@jflamy.dev or drop the file in a comment for this issue.

**Comment by janghelsaket758** [comment]
[owlcmsDatabase_2024-06-23_20h24.json](https://github.com/user-attachments/files/15945105/owlcmsDatabase_2024-06-23_20h24.json)

I have exported the database and attached the file in the comment of this issue. Please see the details below:
Here's an example description in English:


I hope this description is helpful. Feel free to add any more details if necessary.

**Comment by jflamy** [comment]
On a fresh install of 49.0.1 (uninstalled previous version, installed the new one), the json file you sent loads fine.

Note that I cleared the "Championship" filter to see the athletes -- the championship filter defaults to the first championship but you have no athletes in the Open categories.  I suggest you unselect your Open categories from the age group file.

Because this simple fix works fine I am closing the issue.
I do recommend that people always take a json backup before updating.

![Image](https://github.com/jflamy/owlcms4/assets/678663/28878a27-dbed-4363-9d5a-0cc45062de1f)
