### ISSUE TITLE
Updates Attempt Board in Owlcms4

### ISSUE THREAD

**Issue by janghelsaket758** [jflamy/owlcms4#1016]
Attempt Number:

Attempt Indicator:
Show the current attempt number in red (e.g., "2") at the bottom left.
Status Indicator:

Lift Status:
Include a barbell icon or indicator on the right side to signify the lift status.
Adding Animations or Videos:
Good Lift Animation:

When a lift is successful, trigger an animation or video that displays "Good Lift" in a celebratory manner.
Example: Confetti animation with a "Good Lift" text overlay.
No Lift Animation:

When a lift is unsuccessful, trigger an animation or video that displays "No Lift" in a clear and noticeable manner.
Example: A red "X" animation with a "No Lift" text overlay.
Implementation Steps:
Update OWLCMS4 Configuration:

Access the OWLCMS4 settings and customize the attempt board layout to match the described design.
Use CSS to adjust the visual elements to ensure they match the provided example (colors, font sizes, positioning).
Integrate Animations/Videos:

Use JavaScript or a compatible plugin to trigger animations or videos based on the lift outcome.
Store the "Good Lift" and "No Lift" animations/videos in a directory accessible by the OWLCMS4 system.
Write a script to detect lift outcomes and play the corresponding animation or video.
Test the Design:

Conduct thorough testing to ensure that the design displays correctly and that animations/videos trigger at the right moments.
Make any necessary adjustments based on test results.
![Screenshot_2024-06-25-21-38-44-876_app revanced android youtube](https://github.com/jflamy/owlcms4/assets/142079970/9f8590e7-6844-4c01-9a64-80f5bbe8c16d)

**Comment by jflamy** [comment]
The design of the attempt board will not be changed in the foreseable future.
- the current attempt is already visible.
- the barbell is already visible
- the decision lights are already visible

You can change many elements of the layout (colors, fonts, even placement) by looking at the CSS files colors.css attemptBoard.css

In order to do animations, use a system like OBS or vMIX.
- you can use the instructions at https://owlcms.github.io/owlcms4-prerelease/#/OBSSceneSwitching to trigger the changes using OBS
- alternately, you can look at https://github.com/nemikor-solutions/wise-eyes for integration to vMIX or others
