### ISSUE TITLE
Option to print single athlete card during weighin

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#142]
As an enhancement I suggest that the system could support printing of athlete cards during weighin to prevent handwriting erros and ensuring that lot numbers etc are fully up-to-date on the athlete card (to be used during the competition)

**Comment by jflamy** [comment]
If the athlete card is printed as the athlete is weighed in,  the start number is not yet available, and will have to be written by hand (if athletes can move categories, it is possible that they will get a different start number since the start number is based on the lot number within a weight category).
So logically there would be two printouts

1.  when the athlete is weighed in, with the athlete's signature, lot number, but no start number, on a full A4 page
2. an option to print after weigh-in (when the start number is available and athletes are in the proper category).  Currently the format used is 2-per-page to save paper, there would have to be an option to print one-per-page  (official IWF athlete cards are full-paged anyway)

**Comment by jflamy** [comment]
It is probably better to hand-write the start numbers, since all the initials would be on the same piece of paper.  Reading through the pages to catch the eventual typo as the start numbers are written is a good cross-check.
