### ISSUE TITLE
Enhancement: Entry total check should be performed immediatelyon field updates

### ISSUE THREAD

**Issue by AJAYDAS75** [jflamy/owlcms4#217]
(edited by moderator)
Entry total check does not emit an error message when the operator changes the snatch, c&j or entry total.  The error message is only produced when submitting the change.

**Comment by jflamy** [comment]
The entry total check is currently performed when the form is updated (when Enter is used or the button clicked).   Since 
- most people at high-level competitions usually provide compliant numbers
- a check is actually performed preventing wrong information from being used
- the correct error message is produced.
there is no actual misbehaviour, and I will classify this as a cosmetic issue.

**Comment by jflamy** [comment]
(moderator comment)
p.s. Please do not use CAPS LOCK when typing. In social media and online forums this is considered the equivalent of screaming.  I have edited your entry.

**Comment by jflamy** [comment]
There is something non-trivial going on preventing simple errors on text fields from being shown.  Errors are getting cleared at the wrong moment.  After several hours, am stumped.
