### ISSUE TITLE
Show leaders from previous groups

### ISSUE THREAD

**Issue by AJAYDAS75** [jflamy/owlcms4#241]
Sir i would like to suggest that two features if added it will be very helpful for the team official during competition i.e display of result of first three place of Group B and Records in the scoreboard.Thank you.

**Comment by jflamy** [comment]
Not obvious how to do; the only thing that comes to mind have a different scoreboard for use with "single category per group", Competitions with multiple groups for a single category typically have fewer lifters per group, which leaves room for the additional information.
Otherwise, if several categories are merged in a single group, there is no way to show the leaders for multiple groups.  That would require a separate leaderboard with all the leaders from all the currently competing categories and age groups (there could be several)
So a "single-category scoreboard and leaderboard" might be doable

**Comment by jflamy** [comment]
Records management will need to wait until I redesign things to associate lifters with one or more age divisions.  A talented 17 year-old could be breaking youth, junior and senior records all at once, not to mention a meet-specific record.
