### ISSUE TITLE
Attempt board not showing attempt correctly

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#287]
This might be a danish only issue. On the attempt board attempt # are shown as [1 forsøg], [2 forsøg] and [3 forsøg] (without the brackets of course). 

The correct way of showing it in danish would be [1. forsøg], [2. forsøg] and [3. forsøg]. It would correspond in english to [1st attempt], [2nd attempt] and [3rd attempt]

Another option would be [Forsøg 1], [Forsøg 2] and [Forsøg 3] corresponding to [Attempt 1], [Attempt 2] and [Attempt 3]

It as a VERY small issue I might add, but maybe there should be introduced a translation option for this?

**Comment by jflamy** [comment]
The format provided by the Danish translator for the attempt board is 
`{0}<sup>{0,choice,1.|2.|3.}</sup> forsøg`
This should have been 
`{0}. forsøg`
using a choice format is not needed because it would have been `{0}{0,choice,1#.|2#.|3#.} forsøg` whic hreads -- print the number ({0]) and then, if the number is 1 (1#) print a ., if the number is 2 (2#) print a . and if the number is 3 (3#) print a .).
The reason there was no superscript shown is that there was no # in the choice pattern.

**Comment by jflamy** [comment]
Fixed in the translation4.csv master file.

**Comment by AndersBIK99** [comment]
Got it! I misunderstood the format.

So that turned out to be an easy fix 😉

Den søn. 19. jan. 2020 kl. 15.31 skrev Jean-François Lamy <
notifications@github.com>:
