### ISSUE TITLE
OWLCMS read-only rights / athlete-facing attempt board without password

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#542]
Monsieur Lamy,

We have been using OWLCMS with much pleasure the last couple of events in NL. From the last 8 events, I have been involved in the set-up at least 7 times. However, this weekend is a competition which is organized by our Powerlifting Federation, and they take care of amongst others the livestream. For this livestream, I have to provide the scoreboard (no problem) and the athlete-facing attempt board. For the latter, I have to give the password for them to open the board.

Personal conflicts incoming: I don't like this, especially because the person setting up the livestream is the brother of a coach, who has a number of athletes who are in the lower tier of the rankings but are still able to qualify for the nationals. In theory, with the password, the brother could change around some things in OWLCMS.

Perhaps I'm not looking correctly and probably you have already thought about this, but I would like to have the athlete-facing attempt board not being behind a password or a way to put in a password that only grants read-only rights so people cannot go around and change things in the system.

**Comment by scottgonzalez** [comment]
I agree the attempt board should be publicly available for use with the livestream. This is what was just used for Junior Pan Ams.

On a side note, shouldn't you be using the regular attempt board instead of the athlete-facing attempt board so that the decision lights are in the correct order? It also seems like the public referee decision screen is reversed; it matches the athlete facing decision screen instead of matching the attempt board.

**Comment by jflamy** [comment]
The only way I see around your predicament is to have a second password for the displays, distinct from the officials' screens.
By leaving the second password blank the displays would effectively be public.  Will look at what this entails.

**Comment by jflamy** [comment]
The athlete facing screen only exists in the athlete-facing variety.
The attempt board exists in both the athlete-facing and public-facing varieties.  In order to get decision lights for TV, the standard way is to crop out whatever piece of the attempt board is found to be useful, or to use the "current athlete" display that shows the same information as the attempt board but horizontally, plus the previous attempts / ranks / total
I will be working on more tv-oriented screens (start list, medals) with the ability to get the nauseating green background for color-coding transparency.

**Comment by JDFS404** [comment]
Sorry, I think Attempt Board is sufficient (the one with the previous attempts as well right?)

I wanted something like this (would be ideal):
![image](https://user-images.githubusercontent.com/26678110/198384323-6d41068c-5b8e-4b6c-9d9e-e36a52e44b0e.png)

Maybe there's already a way to 'parse' it

**Comment by jflamy** [comment]
That screen is the "current athlete" screen -- bottom section of the Displays.
I don't understand what you mean by "parse" it.

**Comment by jflamy** [comment]
Normally when video people use it, they simply crop the parts they want.

**Comment by JDFS404** [comment]
@jflamy I thought maybe that display is also 'open' for public i.e. no password needed for OWLCMS itself. But I guess this isn't open, that's okay for now since I just gave the password for OWLCMS to the video streaming person (this picture is what I myself was dabbling with on OBS). Everytime I open OBS, I need to 'Interact' with the screen to put in the password unfortunately.

So maybe sometime in the future it would be nice to have this Current Athlete screen open, for something like streaming purposes?

**Comment by jflamy** [comment]
For streaming purposes, there is a backdoor option so that the address of the streaming machine without passwords.   BUT currently this assumes that the streamers are trusted -- the backdoor is global.
I would need to make the backdoor apply only to the displays.

**Comment by jflamy** [comment]
By default, no password is required to open the scoreboards and displays
There is now a password for the officials' screens and a password for the displays.
Setting only the officials password protects the competition but access to the displays is allowed.
If a display password is present, it will be required if the user is not already logged in.

**Comment by jflamy** [comment]
Added in 34.4.0-beta01

**Comment by JDFS404** [comment]
Great, I'll test this with ```OWLCMS_DISPLAYPIN``` and ```OWLCMS_PIN```. Once again, thank you for picking up these little Quality of Life/Lifting improvements :)

**Comment by JDFS404** [comment]
By the way, your preliminary links seem to be no longer working: https://github.com/jflamy-dev/owlcms4-prerelease/releases

**Comment by jflamy** [comment]
I only use jflamy (for the original source) and owlcms (for releases and pre-releases).
This is because github does not allow cloning inside a single account and originally the release directories were clones.

jflamy-dev has been out of use for quite a while now.  Please tell me where you got the link from so I can fix it.

**Comment by JDFS404** [comment]
@jflamy they're in Release Repositories: https://github.com/jflamy/owlcms4/releases/tag/4.4.2-rc2

BTW, have been testing the beta and it works perfectly :) - will use the beta during the comp tomorrow. I doubt it'll break. Thanks so much for this!

**Comment by jflamy** [comment]
Well, that's months ago.  Current releases start with 34.
The beta is the same as what we just ran PanAm JR (300+ athletes, 2 platforms, 4 simultaneous age group competitions), except for tiny tweaks.  It's in beta the time it takes for people to translate the strings I add -- and for me to add tiny peripheral changes.

**Comment by jflamy** [comment]
@JDFS404 I have found the location for the broken links.  The owlcms4 repository does not contain actual releases. I had copied the index table in a "fake" release but forgotten about updating it.   Is now fixed.
