### ISSUE TITLE
Athlete-facing display bug in display

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#551]
**Describe the bug**
See screenshot, text is falling away when a lot of KGs are used

**owlcms version**
Latest

**To Reproduce**
1. Put in a lot of KGs

**Expected behavior**
Correct spacing

**Screenshots**
![image](https://user-images.githubusercontent.com/26678110/198987207-d786c6c5-f529-42f1-8a2e-fdac75d8dbb8.png)

**Comment by JDFS404** [comment]
Hmm strange, must be because the software by default selects 1 red plate and 1 blue plate in the settings. Thanks

**Comment by jflamy** [comment]
The current version of the software only allows to change the number of
reds. The other items are check boxes.

-- 
(Envoyé de mon téléphone mobile.)

**Comment by scottgonzalez** [comment]
Technically there is a bug in the layout, but practically I'm not sure that it matters. The problem is that the sizes are currently based on viewport height, so if an odd aspect ratio is used for the size of the window, the elements will overlap (as the viewport gets narrower, there is less space for all three elements, but the height is not changing, so the size of the elements are not changing). Generally these displays will always be fullscreen (or at least very close) and all common screen resolutions have aspect ratios that should allow the elements to display correctly.

**Comment by jflamy** [comment]
The layout works for all common laptop, phone, tablet and screen resolutions in landscape mode.  Sizes are relative to screen size. and the disk/plates layout has been computed for legitimate plate scenarios.
