### ISSUE TITLE
Support Fixed-duration breaks between groups

### ISSUE THREAD

**Issue by AndersBIK99** [jflamy/owlcms4#616]
**Is your feature request related to a problem? Please describe.**
Often coaches are asking about breaks between groups and snatch and C&J. Often the breaks vary depending on the number of athletes in the groups.

**Describe the solution you'd like**
When creating the groups it would be nice to be able to type in number of minutes between snatch and C&J, and also the length of the break following the group

The entered information should then be printed on appropiate lists. It would be a great enhancement with a time schedule list showing the groups and associated breaks

**Comment by scottgonzalez** [comment]
Time between groups is always dynamic, but the time the next group starts
is already known, so that could be displayed with no additional data entry.

Time between snatch and clean and jerk would have to be provided. If this
is added, it could be used to auto-populate the break time once the snatch
session ends.

**Comment by AndersBIK99** [comment]
In Denmark it is very common to have fixed breaks between groups and thus varying start times.

**Comment by jflamy** [comment]
Even if "fixed breaks" the competition cannot start earlier than 2hours after the weigh-in.
In Quebec we have a rule that if 9 athletes or more there is NO break after snatch because athletes have enough time to get ready -- due to long travel distances we have to do competitions in one day and we often have two platforms with 60-65 athletes each.
In Denmark I would think that the minimum break between the end of a session and the next introductions is always the same ?

**Comment by jflamy** [comment]
In short, I wouldn't have an issue with adding the Snatch-CJ break duration.

**Comment by jflamy** [comment]
If there is a fixed duration for breaks, this can be published in the competition rules.  You still need to publish a weigh-in time, but you can leave the start time empty.
The announcer can schedule a duration immediately at the end of the previous group, and the length of the snatch/CJ break is customizable depending on the number of athletes in the group.
