### ISSUE TITLE
Exclude custom lifters to break records

### ISSUE THREAD

**Issue by danirueda** [jflamy/owlcms4#640]
## Problem
There are lifters living in my region joined in federations from other regions. I load records file from my region but they can´t break that records when sometimes they compete here.

## Posible solution
It would be nice to have some checkboxes in athlete form like _Eligible for individual ranking_, one per each federation records file loaded, to exclude that athlete to break federation records.

![2023-03-07_21-17](https://user-images.githubusercontent.com/16139263/223544266-eaa8bb41-cf5a-430e-acc6-055cf13dc09f.png)

**Comment by scottgonzalez** [comment]
The field on the bottom right is what you're looking for. See https://jflamy.github.io/owlcms4/#/Records?id=eligibility-criteria for more information.

**Comment by jflamy** [comment]
As Scott says, the "Federation donde atleta puede batir records" is the field you want.  Because it is empty, there are no restrictions.  Put the athlete's own federation(s) in the field.  Since an invited lifter won't match any of your loaded records, there will not be any records awarded to that person.
Or as a trick, just type "nil".  There is no "nil" federation, so there will not be any records.

**Comment by danirueda** [comment]
Oh sorry! My fault. Didn't notice for that feature.

Thank you!
