### ISSUE TITLE
Scoreboard shows wrong next lifter after attempt

### ISSUE THREAD

**Issue by jarble7** [jflamy/owlcms4#71]
After the lift is successful or failed, the next lifter on the Results Scoreboard is always the next lift of the lifter that just went, then after 5 seconds changes to the correct lifter.

I have a video that shows the issue
[OWLCMS-scoreboard-issue-1.mkv.zip](https://github.com/jflamy/owlcms4/files/3199782/OWLCMS-scoreboard-issue-1.mkv.zip)

**Comment by jflamy** [comment]
Ah ok.  That's during the time the result for the previous lift is being shown. Will need to investigate.

**Comment by jflamy** [comment]
Testing what happens when I reply to the message.  If you get this copy, send e-mail.

Jean-François Lamy

De : jarble7
Envoyé le :20 mai 2019 16:47
À : jflamy/owlcms4
Cc : Subscribed
Objet :[jflamy/owlcms4] Scoreboard shows wrong next lifter after attempt(#71)

After the lift is successful or failed, the next lifter on the Results Scoreboard is always the next lift of the lifter that just went, then after 5 seconds changes to the correct lifter.
I have a video that shows the issue
OWLCMS-scoreboard-issue-1.mkv.zip

**Comment by jarble7** [comment]
received

Brock Pedersen

**Comment by jflamy** [comment]
First analysis: bottom part appears to get the update message before the lifting order has been computed (once the decision is shown, all goes back to normal).   Does not appear to be systematic, could be a race condition.

**Comment by jflamy** [comment]
lifting order was recomputed too late -- moved up to just after showing the decision lights.  Also recomputed if the refs change their mind in the 3 seconds period after.
