### ISSUE TITLE
Issue in deploying OWLCMS from Raspberry Pi via Docker

### ISSUE THREAD

**Issue by JDFS404** [jflamy/owlcms4#832]
**Describe the bug**
Trying to setup OWLCMS in a Docker environment on Raspberry Pi OS for another club - they will host OWLCMS in the cloud. When trying to run OWLMS, the following error is given:
`exec /opt/java/openjdk/bin/java: exec format error`

Perhaps the Java path is wrong? I also installed JDK via `sudo apt install default-jdk`.

**owlcms version**
`stable`

**To Reproduce**
Deploy OWLCMS in Docker running the `stable` version

**Desktop (please complete the following information):**
Running on Raspberry Pi OS on a Raspberry Pi 4. Just to give some background, no issues on my Unraid server running on Intel (ASRock J4205-ITX).

**Comment by JDFS404** [comment]
My Java path is apparently as follows: `/usr/lib/jvm/java-17-openjdk-arm64/`

Is it not possible to run OWLCMS on an ARM architecture?

**Comment by jflamy** [comment]
The Docker images I provide are x64, not ARM.
You can run the program on RaspberryOS directly - just copy the zip from the release directory.
unzip, and then `java -jar owlcms.jar`  where you unzipped the files.  

There is really no advantage in running it in Docker though because you need to allocate a volume for the database, etc.

If you want to do your own Dockerfile you are welcome to do it, you would simply pull the zip from the release directory using wget or curl, and start it.

**Comment by JDFS404** [comment]
Interesting - I wasn't aware of that. Would it then be possible to run multiple instances of OWLCMS on 1 RaspberryOS? Let's say `owlcms.jar` and `owlcms1.jar`?

Reason is: we want to check if we can deploy multiple instances and make them available through a CloudFlare proxy behind our federation's website. I'm doing that now via my own Unraid server, but that one is overkill to host OWLCMS.

**Comment by jflamy** [comment]
The `/opt/java/openjdk/bin/java` is where the container has its java (inside the container).  When the ARM Docker engine loads the container and tries to run that, it realizes that it is not an ARM binary.

**Comment by jflamy** [comment]
Honestly, you're giving yourself a lot of trouble for nothing.  Just create one site per club on fly.io.  Then attach the pretty site name you want to each site since you likely own a domain (it's just a matter of adding a DNS entry) You won't have to worry about performance and bandwidth.  There is a local cloud server in Amsterdam.

Now if you really want to have several owlcms on the same machine, no problem.
The simplest way is to simply copy the unzipped directory as many times as you want
~/club1  ~/club2
then start each club on a different port.

cd ~/club1; java -Dport=8081 -jar owlcms.jar
cd ~/club2; java -Dport=8082 -jar owlcms.jar

You can then use caddy as a reverse proxy to direct the traffic to  club1.yourfederation.nl
For each site the Caddyfile would have something like

club1.yourfederation.nl {
        reverse_proxy 127.0.0.1:8081
        skip_log
}
