### ISSUE TITLE
publicresults timer behavior on page refresh

### ISSUE THREAD

**Issue by jflamy** [jflamy/owlcms4#866]
Timer should not restart - investigate why the time is not recomputed.
Perhaps use the restore-on-refresh feature from Vaadin.

**Comment by jflamy** [comment]
fixed using absolute time.

**Comment by scottgonzalez** [comment]
Using absolute time causes issues when the local server does not have its clock set correctly. Rather than using the start timestamp supplied by server, it would be more resilient to get a local timestamp when the event occurs. While this can cause a slight drift due to network latency, the drift would be the same that would have existed prior to this change.

**Comment by scottgonzalez** [comment]
The change requested above is tracked in gh-930.
